[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ["openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@uniswap/v3-core/=lib/v3-core/",
    "@uniswap/v3-periphery=lib/v3-periphery/",
    "uniswap/v3-core/=lib/v3-core/",
    "uniswap/v3-periphery=lib/v3-periphery/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
